Analisador semantico
DesignLiquido/portugol-studio pull request #29
Opened 2024-06-18 18:24 UTC by Aristidescosta

esboço do `analisador`

2024-06-21 14:34 UTC, samuelrvg requested changes

2024-06-21 14:34 UTC, samuelrvg commented on fontes/analisador-semantico/analisador-semantico-portugol-studio.ts
> +            console.log(declaracoes[this.atual])
Remover console.log

2024-06-21 14:34 UTC, samuelrvg commented on fontes/analisador-semantico/analisador-semantico-portugol-studio.ts
> +        console.log(declaracao)
Remover console.log

2024-06-21 14:34 UTC, samuelrvg commented on fontes/analisador-semantico/analisador-semantico-portugol-studio.ts
> +        console.log(declaracao)
Remover console.log

2024-06-22 09:13 UTC, Aristidescosta commented on fontes/analisador-semantico/analisador-semantico-portugol-studio.ts
> +        console.log(declaracao)
Essa Pr subi para uma análise do Sr. Leonel, pois por algum motivo o teste não entre nós demais métodos do analisador, somente no método **analisar**

2024-07-07 17:52 UTC, leonelsanchesdasilva requested changes
Está excelente. Pedi alguns ajustes.

2024-07-07 17:52 UTC, leonelsanchesdasilva commented on jest.config.ts
> +            '@designliquido/delegua/(.*)': '<rootDir>/node_modules/@designliquido/delegua/fontes/$1'
@Aristidescosta Favor comentar esta linha e descomentar a linha 12.

2024-07-07 17:52 UTC, leonelsanchesdasilva commented on tsconfig.json
> -            // "@designliquido/delegua/*": ["node_modules/@designliquido/delegua/fontes/*"],
@Aristidescosta Favor usar o formato das barras duplas.

2024-07-07 18:35 UTC, leonelsanchesdasilva approved these changes

2024-07-07 18:36 UTC, merged